CREATE DATABASE great_bay;

USE great_bay;

CREATE TABLE open_items (
    ID INTEGER(10) auto_increment primary key,
    ITEM_DESCRIPTION VARCHAR(100) NOT NULL,
    CURRENT_BID INTEGER(10) NOT NULL,
    TIME_LEFT TIME,
    HIGHEST_BIDDER_NAME VARCHAR(10) NOT NULL
)

CREATE TABLE closed_items (
    ID INTEGER(10) auto_increment primary key,
    ITEM_DESCRIPTION VARCHAR(100) NOT NULL,
    WINNING_BID INTEGER(10) NOT NULL,
    HIGHEST_BIDDER_NAME VARCHAR(10) NOT NULL
)

CREATE TABLE users (
    ID INTEGER(10) auto_increment primary key,
    USERNAME VARCHAR(10) NOT NULL,
    PASSWORD VARCHAR(10) NOT NULL
)